### ISSUE TITLE
Can't use same trigger command for multiple reactions

### ISSUE THREAD

**Issue by rafitamolin** [WiredSpast/G-Trigger#1]
In my case, I want to make a command that writes multiple things in my behalf in chat. As I can see, if I write the command, it only triggers the first reaction added, it doesn't trigger the next ones.

![](https://i.imgur.com/y0d3BMD.png)

_(In this screenshot, only the first trigger happens, the shout one, the chat one isn't being triggered)_

**Comment by WiredSpast** [comment]
This isn't a bug in G-Trigger, it's a rate limit by Habbo, try raising the delay for the second packet some more
