### ISSUE TITLE
The "consume" option is not pre-checked

### ISSUE THREAD

**Issue by brianmonteiro54** [WiredSpast/G-Trigger#3]
The consume option is not pre-checked and does not have the option to activate all consumptions at once.

<picture>
  <img alt="control tab" src="https://i.imgur.com/WVIWgMo.png">
</picture>

Also in save / load only the load option appears

<picture>
  <img alt="save / load" src="https://i.imgur.com/n1bMMT7.png">
</picture>

**Comment by WiredSpast** [comment]
That's supposed to be like that, but if all of your entries have the same trigger it's enough to mark consume on 1 of them.

I can look into adding a consume all option tho.

And yeah that Save/Load tab wasn't fully implemented yet.
